name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --no-cache --platform linux/amd64 -t 3ltreilly/hay-logger .
    - name: push to docker hub
      run: docker push 3ltreilly/hay-logger
